%Add main effect and difference wave bins to each subject
%
%Author: Eric Fields
%Version Date: 27 March 2019

%% Set-up

clearvars; close all;

main_dir = 'Z:\Bowen, Holly\EmoRecap_ERP\EEGLAB_Analysis\DATA';

subject_ids = get_subset('erp', [], main_dir);

%% Add bins

for i = 1:length(subject_ids)
    
    %Get sub id
    sub_id = subject_ids{i};
    
    %Start/re-start EEGLAB
    [ALLEEG, EEG, CURRENTSET, ALLCOM] = eeglab;
    
    %Load ERPset
    ERP = pop_loaderp('filename', [sub_id '.erp'], ... 
                      'filepath', '\\brain510.bc.edu\labsharefolder\Bowen, Holly\EmoRecap_ERP\EEGLAB_Analysis\DATA\ERPsets\');
    ALLERP = ERP;
    CURRENTERP = 1;
    
    %Add bins
    ERP = pop_binoperator(ERP, ...
                          {'b120 = b18-b16 label Neg-Neu_Retrieval_diff', ...  
                           'b121 = b17-b16 label Pos-Neu_Retrieval_diff', ...
                           'b122 = b18-b17 label Neg-Pos_Retrieval_diff', ...
                           'b123 = b68-b66 label Neg-Neu_Remember&Know_diff', ...
                           'b124 = b67-b66 label Pos-Neu_Remember&Know_diff', ...
                           'b125 = b68-b67 label Neg-Pos_Remember&Know_diff', ...  
                           'b126 = b28-b26 label Neg-Neu_Remember_diff', ... 
                           'b127 = b27-b26 label Pos-Neu_Remember_diff', ...
                           'b128 = b28-b27 label Neg-Pos_Remember_diff', ...
                           'b129 = b38-b36 label Neg-Neu_Know_diff', ...
                           'b130 = b37-b36 label Pos-Neu_Know_diff', ...
                           'b131 = b38-b37 label Neg-Pos_Know_diff', ...
                           'b132 = b78-b76 label Neg-Neu_Guess&New_diff', ...  
                           'b133 = b77-b76 label Pos-Neu_Guess&New_diff', ...
                           'b134 = b78-b77 label Neg-Pos_Guess&New_diff', ...  
                           'b135 = b48-b46 label Neg-Neu_Guess_diff', ...
                           'b136 = b47-b46 label Pos-Neu_Guess_diff',...
                           'b137 = b48-b47 label Neg-Pos_Guess_diff', ...
                           'b138 = b58-b56 label Neg-Neu_New_diff', ...
                           'b139 = b57-b56 label Pos-Neu_New_diff', ...
                           'b140 = b58-b57 label Neg-Pos_New_diff', ... 
                           'b141 = b82-b19 label Old-New_diff', ...
                           'b142 = b66-b19 label NEURemKnow-New_diff', ...
                           'b143 = (b67+b68)/2 label Pos&Neg_All_Remember&Know', ...
                           'b144 = b143 - b66 label Emo-Neu_Remember&Know_diff', ...
                           'b145 = b66 - b79 label NeuRem&Know-DistractorGuess&new_diff', ...
                           'b146 = b26 - b79 label NeuRem-DistractorGuess&New', ...  
                           'b147 = b36 - b79 label NeuKnow-DistractorGuess&New', ...
                           'b148 = b46 - b79 label NeuGuess-DistractorGuess&New', ...
                           'b149 = b56 - b79 label NeuNew-DistractorGuess&New', ...
                           'b150 = b76 - b79 label NeuGuess&New-DistractorGuess&New', ...
                           'b151 = (b60+b62+b64)/3 label All_Face_Remember&Know', ...
                           'b152 = (b61+b63+b65)/3 label All_Scene_Remember&Know', ...
                           'b153 = (b70+b72+b74)/3 label All_Face_Guess&New', ...
                           'b154 = (b71+b73+b75)/3 label All_Scene_Guess&New', ...  
                           'b155 = (b151-b152) label Face-Scence_Remember&Know_diff'});           
    ALLERP(CURRENTERP) = ERP;
    
    %Save ERPset
    ERP = pop_savemyerp(ERP, 'erpname', sub_id, 'filename', [sub_id '.erp'], ... 
                        'filepath', '\\brain510.bc.edu\labsharefolder\Bowen, Holly\EmoRecap_ERP\EEGLAB_Analysis\DATA\ERPsets');
    
end

eeglab redraw;
erplab redraw;
