%Make difference bins for EmoRecap ERP
%
%Author: Eric Fields
%Version Date: 27 June 2018

ERP = pop_binoperator(ERP, {'b120 = b18-b16 label Neg-Neu_Retrieval_diff', ...  
                            'b121 = b17-b16 label Pos-Neu_Retrieval_diff',...
                            'b122 = b18-b17 label Neg-Pos_Retrieval_diff', ...
                            'b123 = b68-b66 label Neg-Neu_Remember&Know_diff', ...
                            'b124 = b67-b66 label Pos-Neu_Remember&Know_diff',...
                            'b125 = b68-b67 label Neg-Pos_Remember&Know_diff', ...
                            'b126 = b28-b26 label Neg-Neu_Remember_diff', ...
                            'b127 = b27-b26 label Pos-Neu_Remember_diff',...
                            'b128 = b28-b27 label Neg-Pos_Remember_diff',...
                            'b129 = b38-b36 label Neg-Neu_Know_diff',...
                            'b130 = b37-b36 label Pos-Neu_Know_diff',...
                            'b131 = b38-b37 label Neg-Pos_Know_diff', ...  
                            'b132 = b78-b76 label Neg-Neu_Guess&Know_diff', ...
                            'b133 = b77-b76 label Pos-Neu_Guess&Know_diff',...
                            'b134 = b78-b77 label Neg-Pos_Guess&Know_diff', ...
                            'b135 = b48-b46 label Neg-Neu_Guess_diff', ...
                            'b136 = b47-b46 label Pos-Neu_Guess_diff',...
                            'b137 = b48-b47 label Neg-Pos_Guess_diff', ...
                            'b138 = b58-b56 label Neg-Neu_New_diff', ...
                            'b139 = b57-b56 label Pos-Neu_New_diff',...
                            'b140 = b58-b57 label Neg-Pos_New_diff'});
                        
eeglab redraw; erplab redraw;
